version: "3"
services:
    poapbot:
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        command: bash -c "python db_init.py && uvicorn poapbot.app:app --host 0.0.0.0 --port 8000"
        ports:
            - 8000:8000
        volumes:
            - "./:/app"