reddit:
  auth:
    username: POAPbot
    password: 
    client_id: 
    client_secret: 
    user_agent: "POAPbot by /u/Bad_Investment https://github.com/badinvestment/poap-reddit-bot"

db:
  url: sqlite:///test.db

poap:
  url: https://poap.xyz/claim/

fastapi:
  title: Reddit POAP Bot
  version: 0.1.0
  openapi_tags:
    - name: admin
    - name: events
    - name: claims
    - name: export
    - name: scrape